---
- hosts: mongosvrs
  become: yes
  become_method: sudo
  become_user: root
  tasks:
    - name: stop and remove all containers
      shell:
        cmd: (docker stop $(docker ps -aq) || true) && (docker rm $(docker ps -aq) || true)
      tags: clear-container
