---
- hosts: mongosvrs
  become: yes
  become_method: sudo
  become_user: root
  tasks:
    - name: docker pull mongo
      shell:
        cmd: docker pull mongo:latest
      tags: pull-mongo
    - name: make /mnt/mongo-cluster/ directory
      file: path=/mnt/mongo-cluster state=directory
    - name: make /mnt/mongo-cluster/configsvr directory
      file: path=/mnt/mongo-cluster/configsvr state=directory
    - name: make /mnt/mongo-cluster/mongos directory
      file: path=/mnt/mongo-cluster/mongos state=directory
    - name: copy configsvr file to /mnt/mongo-cluster/configsvr folder
      copy: src=conf/mongo-cfgsvr.conf dest=/mnt/mongo-cluster/configsvr/mongod.conf
      tags: copy-config
    - name: copy mongos file to /mnt/mongo-cluster/mongos folder
      copy: src=conf/mongo-mongos.conf dest=/mnt/mongo-cluster/mongos/mongos.conf
      tags: copy-mongos
    - name: copy template file to /mnt/mongo-cluster folder
      copy: src=conf/mongo-shardsvr.tmpl dest=/mnt/mongo-cluster/mongo-shardsvr.tmpl
      tags: copy-shard
    - name: generate shard{1,2,3} directory and config file
      shell:
        cmd: for number in `seq 1 3`; do mkdir -p ./shard${number} && NUMBER=${number} envsubst < ./mongo-shardsvr.tmpl > ./shard${number}/mongod.conf; done
        chdir: /mnt/mongo-cluster
    - name: create and start docker config server container
      shell:
        cmd: docker run -d -ti --name mongo-cfg -p 27019:27019 --restart always -v /mnt/mongo-cluster/configsvr:/etc/mongodb mongo:latest -f /etc/mongodb/mongod.conf
      tags: start-config
    - name: create and start docker shard containers
      shell:
        cmd: for number in `seq 1 3`; do docker run -d -ti -p 2701${number}:2701${number} --restart always --name mongo-shard${number} -v /mnt/mongo-cluster/shard${number}:/etc/mongodb mongo:latest -f /etc/mongodb/mongod.conf; done
      tags: start-shard
    - name: create and start docker mongos container
      shell:
        cmd: docker run -d -ti --name mongo-mongos  -p 27020:27020 --restart always -v /mnt/mongo-cluster/mongos:/etc/mongodb --entrypoint "mongos" mongo:latest -f /etc/mongodb/mongos.conf
      tags: start-mongos
