---
- hosts: rabbitmqsvrs
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: add hosts to /etc/hosts
      shell:
        cmd: |
          cat >> hosts << EOF
          172.27.0.12 rabbitmq1@rabbitmq1
          172.27.0.13 rabbitmq2@rabbitmq2
          172.27.0.4 rabbitmq3@rabbitmq3
          EOF
        chdir: /etc/
